{% set name = "lrslib" %}
{% set version = "71.a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://cgm.cs.mcgill.ca/~avis/C/lrslib/archive/lrslib-0{{ version.replace(".", "") }}.tar.gz
  sha256: 926636ea68de46625f141f6e025dce967cc7e68cf4bf4a597375c063f5c11673

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - coreutils
    - sed
    - make
  host:
    - gmp

test:
  requires:
    - curl
  commands:
    - test -f $PREFIX/lib/liblrs${SHLIB_EXT}
    - test -f $PREFIX/include/lrslib/lrslib.h
    - curl -L -O http://cgm.cs.mcgill.ca/~avis/C/lrslib/archive/test_files/lrs/bv7.ine
    - redund bv7.ine

about:
  home: http://cgm.cs.mcgill.ca/~avis/C/lrs.html
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: lrslib is a self-contained ANSI C implementation of the reverse search algorithm for vertex enumeration/convex hull problems
  doc_url: http://cgm.cs.mcgill.ca/%7Eavis/C/lrslib/USERGUIDE.html

extra:
  recipe-maintainers:
    - isuruf
