travis:
  secure:
    BINSTAR_TOKEN: YMtyUuv/OureIdTtO7FMge9WtBSs3oFKxGp3rVfJR/Q0PtcWjO/0G+W3PUXmuXAdzIfgz33StpCCOcr44vz2fbEsxErfyRKR6jdAsZTfflkmQlT/sBzJaOA/sR6/71wvB3O8YLA7Zw3A6cixSqiNQBjL/OrI+atURvm1AYMaHZqDUtJV6WGi+mBz+PRM/fdWi6MLsI5OuJ7KfA/BAbt306Bejgj7Jl54hCYdvP/9l9InZDoUkfnzGHVv5Jouua4zfs81vUe/XuxOn3d3q5HQKo7GK5pUC7xWm255a+zuI3DZr450xtN+5edIjPN6BxqFLy8LvCLpCFBKsogTirC5pYUDYM2Smrk67eauDQpapph1JoLhRpS6zl3b8aTd328iSBOrQg29k48mubvn4Sb+qQyIqVC2e0cBek3+snOSkQP7RkeOXHFeyKDq2OpZvYUFlTjMWakwGHeBQXEvy66+Ein39R8FYErEjRzjYki1UUtZX1oBW48P5lSX/GGgGRXfh6Qm8kzlyjldJEbYmoduw0kGoOYFb4/yKdQERSTlqpDyjBO5mfNZqT4rOaLYjp9pp+x49eOUCjJ2+As4stMSYqGMEHvt7U/SVc4l3AS1hcFTEWCujm2x5TYs4GVAyy52QJTpZPA0nx8BjJVo/2u9r2czteY1CX9AplKide8bFpU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
